# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release Core

on:
  push:
    tags:
      - "v*.*.*" # Triggers on tags like v1.0.0, v2.1.5, etc.

env:
  NET_VERSION: 9.0
  NUGET_PATH: "./**/Dapps.CqrsCore.Persistance.${{ github.event.release.tag_name }}.nupkg"
  PROJECT_PATH: "./Dapps.CqrsCore.Persistance/Dapps.CqrsCore.Persistance.csproj"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET ${{ env.NET_VERSION }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.NET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release /p:Version=${{ github.ref_name != null && startsWith(github.ref_name, 'v') && github.ref_name[1:] || github.ref_name }} --no-restore
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            # Release Notes for ${{ github.ref_name }}
            - List of changes
            - Bug fixes
          draft: false
          prerelease: false
      - uses: actions/upload-artifact@v4
        with:
          name: NuGet
          path: ${{ env.NUGET_PATH }}
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
